### ISSUE TITLE
Errors on layouts

### ISSUE THREAD

**Issue by iandoug** [CTGAP/ctgap-keyboard-layout#1]
Hi

checking ctgap-2.en.ergodox
Error with ctgap-2.en.ergodox.json : ctgap-2.en.ergodox, duplicate character on keyboard: / (47) 
Error with ctgap-2.en.ergodox.json : ctgap-2.en.ergodox, duplicate character on keyboard: ? (63) 
 Error with ctgap-2.en.ergodox.json : ctgap-2.en.ergodox, characters not on keyboard: ;: 

checking ctgap-31.en.ergodox
 Error with ctgap-31.en.ergodox.json : ctgap-31.en.ergodox, duplicate character on keyboard: / (47) 
Error with ctgap-31.en.ergodox.json : ctgap-31.en.ergodox, duplicate character on keyboard: ? (63) 
 Error with ctgap-31.en.ergodox.json : ctgap-31.en.ergodox, characters not on keyboard: ;:

**Comment by CTGAP** [comment]
The punctuation issue with CTGAP 2.0 has been resolved. CTGAP 3.1 was not meant to be public and thus has been removed.

**Comment by iandoug** [comment]
Thanks, have deleted 3.1, 2 checks ok.

Cheers, Ian
